server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
      - id: hello_route
        uri: http://localhost:8088/api/hello
        predicates:
        - Path=/api/hello
logging:
  level:
    io.github.kimmking: DEBUG
    org: INFO
